services:
  postgres:
    image: postgres:17
    container_name: local_postgres
    restart: always
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=salarly_local
    ports:
      - '5434:5432' # Expose the Postgres port to your local machine
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
