name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    if: ${{ github.repository == 'Techarmadon/salarly' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # ✅ Enable pnpm via Corepack
      - name: Enable pnpm
        run: corepack enable

      # lock pnpm version
      - name: Use pnpm version
        run: corepack prepare pnpm@10 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # ✅ Generate Prisma Client
      - name: Prisma Generate
        # env:
        # DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}
        run: pnpm --filter @salarly/database generate

      # ✅ Deploy migrations
      - name: Prisma Migrate Deploy
        # env:
        # DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}
        run: pnpm --filter @salarly/database db:migrate:deploy

      # - name: Pull Vercel Environment Information
      #   run: pnpm dlx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN

      # - name: Build Project Artifacts
      #   run: pnpm dlx vercel build --token=$VERCEL_TOKEN

      # - name: Deploy Project Artifacts to Vercel
      #   run: pnpm dlx vercel deploy --prebuilt --token=$VERCEL_TOKEN
